# Generated by Django 3.2.6 on 2025-03-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey2016',
            name='financially_excluded',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
