# Generated by Django 3.2.6 on 2025-03-22 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_survey2016_financially_excluded'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data2021',
        ),
        migrations.DeleteModel(
            name='Survey2016',
        ),
    ]
